pipeline {
    agent any

    environment {
        AWS_CREDENTIALS_ID = 'aws-access-key' // Jenkins credential ID for AWS IAM credentials
        ACCOUNT_ID = '767828752195' // Your AWS account ID
        REGION = 'us-east-1' // Your AWS region
        BACKEND_IMAGE = "my-express-app:${env.BUILD_ID}"
        ECR_BACKEND_IMAGE = "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/my-express-app:${env.BUILD_ID}"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                git 'https://github.com/kumarsuresh03/Backend.git' // Replace with your repo
            }

        stage('Build Docker Image') {
            steps {
                script {
                    // Build Backend Docker Image
                    docker.build(BACKEND_IMAGE, '.')
                }
            }
        }

        stage('Push Docker Image to AWS ECR') {
            steps {
                withAWS(credentials: AWS_CREDENTIALS_ID, region: REGION) {
                    script {
                        // Login to ECR
                        sh "aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

                        // Push Backend Image
                        sh "docker tag ${BACKEND_IMAGE} ${ECR_BACKEND_IMAGE}"
                        sh "docker push ${ECR_BACKEND_IMAGE}"
                    }
                }
            }
        }
       
    }
}
