pipeline {
    agent any

    environment {
        AWS_CREDENTIALS_ID = 'aws-access-key'
        ACCOUNT_ID = '767828752195'
        REGION = 'us-east-1'
        BACKEND_IMAGE = "my-express-app:${env.BUILD_ID}"
        ECR_BACKEND_IMAGE = "${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/my-express-app:${env.BUILD_ID}"
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/kumarsuresh03/Backend.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('my-express-app') {
                    script {
                        docker.build(BACKEND_IMAGE, '.')
                    }
                }
            }
        }

        stage('Push Docker Image to AWS ECR') {
            steps {
                withAWS(credentials: AWS_CREDENTIALS_ID, region: REGION) {
                    script {
                        // Use bat for Windows
                        bat "aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"
                        bat "docker tag ${BACKEND_IMAGE} ${ECR_BACKEND_IMAGE}"
                        bat "docker push ${ECR_BACKEND_IMAGE}"
                    }
                }
            }
        }
    }
}
